### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by prp-e** [jalmasi/vrspace#25]
I downloaded a jar file and placed it inside `/server` directory and ran it. When I navigate to `http://localhost:8080` I get _Whitelabel Error Page_. I am on macOS big sur and my java version is 14.

**Comment by jalmasi** [comment]
How about http://localhost:8080/babylon/avatar-selection.html ?

**Comment by jalmasi** [comment]
Displaying custom error page now.
