### ISSUE TITLE
Vrspace freezing oculus

### ISSUE THREAD

**Issue by Bernardjpjr** [jalmasi/vrspace#3]
I am having a problem with VRspace on my oculus. this problem makes me restart my oculus before it can function again. It freezes up after I pick the character in the terrain even when searching home. Is there any known fix for this bug?

**Comment by jalmasi** [comment]
Thanks for reporting, I'll try with my oculus.
In the meantime, any more specifics? 
Like, which character does that happen with, any?
When exactly does that happen, when entering a world? If so, which world exactly?

**Comment by Bernardjpjr** [comment]
i used the character male cyclops and 2 others i dont remember their names.
it happens after choosing your terrain while placing it i guess , and
picking an item . i hope this helps .

**Comment by jalmasi** [comment]
Ah so you entered vrcraft world and tried building world in VR? Cool :)
Well that was indeed broken, fixed it, please try again.
