### ISSUE TITLE
unity plugin

### ISSUE THREAD

**Issue by crow34** [jalmasi/vrspace#6]
hi  is it possible to design my own levels in unity or blender or do i have to use the in built editor is there a possible plugin i could use for unity or blender?

thankyou

**Comment by jalmasi** [comment]
Well yes, all models on you can see on vrspace.org are designed like that. You can use any tool that exports glTF, and that's pretty much everything.
With blender glTF add-on you can export either binary (glb) or json+binary (gltf). Both will work, but I prefer the later, just a personal preference I picked from sketchfab. Easiest way to start is naming your file scene.gltf and saving textures in textures/ subfolder.
Much the same with unity, though I didn't try myself. Additionally there's babylon.js exporter for unity - experimental, did not work for me. But I did get my hands on some exported levels, and did add vrspace multi-user stuff, avatars and streams.
