### ISSUE TITLE
I am unable to redirect to other domain. 

### ISSUE THREAD

**Issue by saismm9810** [jalmasi/vrspace#7]
I deployed it on my vps and tried to redirect it, but was unable to do it. can you please guide me how to deoloy it on some other port?  also can you provide me your discord or some social link because we are working on something and it would really help if you can help.

**Comment by jalmasi** [comment]
Scroll all the way down on the home page, there's my contact link.
All config parameters are stored in application.properties file, here's the reference:
https://github.com/jalmasi/vrspace/blob/master/server/src/main/resources/application.properties

First comments in the file explain how to override the entire file, or some specific parameters. In short, you can simply 
 java -jar target/server-0.4.5-SNAPSHOT.jar --server.port=1234
or
java --server.port=1234 -jar target/server-0.4.5-SNAPSHOT.jar

Other than that, I can help you set apache proxy on windows and linux. It's supposed to be documented here: https://redmine.vrspace.org/projects/vrspace-org/wiki#Apache
but is empty for the time being, as we need a reality check. If that's what you need, we may have a go at it now.

**Comment by saismm9810** [comment]
yes, that would be really helpfull if you can please help us in setting the proxy on windows. Sure, lets connect. I have added youbon my linkedin. 
Thanks a lot jalmasi for helping.
